### ISSUE TITLE
Laravel 5.2 and PHPunit issue

### ISSUE THREAD

**Issue by obayesshelton** [solanolabs/solano-phpunit#10]
Hi, 

I seem to be having an issue with Laravel 5.2 and PHPunit, Because I cannot upgrade PHPunit to 5 due to your dependency version I think this could be causing the issue. Have you seen any similar issues? 

[PHP FATAL ERROR: tests/Api/SectorTest.php
vendor/laravel/framework/src/Illuminate/Container/Container.php (line 748):
Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /mnt/home/u12982/src/repo/api/vendor/laravel/framework/src/Illuminate/Container/Container.php:748
Stack trace:
#0 /mnt/home/u12982/src/repo/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /mnt/home/u12982/src/repo/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /mnt/home/u12982/src/repo/api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /mnt/home/u12982/src/repo/api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 [internal function]: Illuminate\Foundation\Bo](url)

**Comment by IsaacChapman** [comment]
I've merged a PR allowing newer versions of PHPunit. Can you run a Solano CI build and point out the build page URL to support@solanolabs.com if you are still having an issue?

**Comment by obayesshelton** [comment]
All our issues have been resolved thanks @IsaacChapman
